In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.preprocessing import StandardScaler

# Example data
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [3]:
from sklearn.preprocessing import MinMaxScaler

# Example data
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(data)

print(scaled_data)

[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


In [4]:
from sklearn.preprocessing import MaxAbsScaler

# Example data
data = [[-1, -2, -3], [4, 5, 6], [7, 8, 9]]

# Initialize the MaxAbsScaler
scaler = MaxAbsScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[-0.14285714 -0.25       -0.33333333]
 [ 0.57142857  0.625       0.66666667]
 [ 1.          1.          1.        ]]


In [5]:
from sklearn.preprocessing import RobustScaler

# Example data
data = [[1, 2, 3], [4, 5, 100], [7, 8, 9]]

# Initialize the RobustScaler
scaler = RobustScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[-1.         -1.         -0.12371134]
 [ 0.          0.          1.87628866]
 [ 1.          1.          0.        ]]


In [6]:
# The Normalizer scales individual samples to have unit norm (i.e., the length of the vector is 1). It’s useful when you want to scale input vectors individually rather than across features.

In [7]:

from sklearn.preprocessing import Normalizer

# Example data
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Initialize the Normalizer
normalizer = Normalizer()

# Fit and transform the data
normalized_data = normalizer.fit_transform(data)

print(normalized_data)


[[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]
 [0.50257071 0.57436653 0.64616234]]
